name: "siglip"
backend: "python"
max_batch_size: 16

input [
  {
    name: "image"
    data_type: TYPE_UINT8
    dims: [3, 384, 384]
  }
]

output [
  {
    name: "embedding"
    data_type: TYPE_FP32
    dims: [1152]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
